# Generated by Django 4.1 on 2023-05-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("calificador_riesgo", models.CharField(max_length=10)),
                ("tipo_riesgo", models.CharField(max_length=255)),
                ("ponderacion_calificacion", models.FloatField()),
                ("alto_riesgo", models.BooleanField()),
            ],
        ),
    ]
